# REopt®, Copyright (c) Alliance for Sustainable Energy, LLC. See also https://github.com/NatLabRockies/REopt_API/blob/master/LICENSE.
from keys_env import *
import os
import django
import rollbar
import sys

"""
Django settings for reopt_api project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

APP_ENV = os.getenv('APP_ENV', os.getenv('DEPLOY_ENV', 'development'))

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secret_key_

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reo',
    'summary',
    'tastypie',
    'proforma',
    'resilience_stats',
    'futurecosts',
    'django_celery_results',
    'django_extensions',
    'reoptjl',
    'ghpghx'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'rollbar.contrib.django.middleware.RollbarNotifierMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'reopt_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'reopt_api.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default':{
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'HOST': db_host,
        'NAME': db_name,
        'OPTIONS': {
            'options': '-c search_path=' + db_search_path
        },
        'USER': db_username,
        'PASSWORD': db_password,
    }
}


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Results backend
CELERY_RESULT_BACKEND = 'django-db'

if APP_ENV == 'staging':
    CELERY_WORKER_MAX_MEMORY_PER_CHILD = 6000000 # 6 GB
else:
    CELERY_WORKER_MAX_MEMORY_PER_CHILD = 4000000 # 4 GB

if 'test' in sys.argv:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES_EXCEPTIONS = False

# we have been resetting celery workers by max memory due to a memory growth problem.
# this problem may be fixed by removing PyJulia, but can't view Rancher metrics yet.
# Once we can confirm that we no longer have a memory grwoth issue we can disable this setting.
# It has to be set according to the RAM available.

# limit number of concurrent workers, by default = number of CPUs
CELERY_WORKER_CONCURRENCY = 1
# controlling number of celery workers with number of celery pods

# celery task registration
CELERY_IMPORTS = (
    'reo.api',
    'reo.scenario',
    'reo.process_results',
    'reo.src.run_jump_model',
    'resilience_stats.outage_simulator_LF',
    'futurecosts.api',
    'futurecosts.tasks',
    'django_extensions',
    'reoptjl.api',
    'reoptjl.src.run_jump_model',
    'ghpghx'
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
if APP_ENV == 'development':
    STATIC_URL = '/static/'
else:
    STATIC_URL = '/'

ROLLBAR = {
    'access_token': rollbar_access_token,
    'environment': APP_ENV,
    'root': BASE_DIR,
    'branch': os.environ.get('BRANCH_NAME')
}
if 'test' in sys.argv or APP_ENV == 'local':
    ROLLBAR['enabled'] = False

rollbar.init(**ROLLBAR)

APPEND_SLASH = False
TASTYPIE_ALLOW_MISSING_SLASH = True
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "reopt_api.settings")
django.setup()
