# Generated by Django 4.2.26 on 2026-02-03 16:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0113_merge_20251209_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='chpoutputs',
            name='electric_curtailed_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Electric power curtailed time-series array [kW]', size=None),
        ),
    ]
