# Generated by Django 4.2.26 on 2026-05-14 22:39

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0113_merge_20251209_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hightempthermalstorageoutputs',
            old_name='storage_to_turbine_series_mmbtu_per_hour',
            new_name='storage_to_steamturbine_series_mmbtu_per_hour',
        ),
        migrations.RenameField(
            model_name='hotthermalstorageoutputs',
            old_name='storage_to_turbine_series_mmbtu_per_hour',
            new_name='storage_to_steamturbine_series_mmbtu_per_hour',
        ),
        migrations.AddField(
            model_name='boileroutputs',
            name='thermal_to_absorption_chiller_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='chpinputs',
            name='follow_electrical_load',
            field=models.BooleanField(blank=True, default=False, help_text='Boolean indicator if CHP follows the electrical load by running at capacity or meeting the load only', null=True),
        ),
        migrations.AddField(
            model_name='chpinputs',
            name='include_cooling_in_chp_size',
            field=models.BooleanField(blank=True, default=False, help_text='Boolean indicator if cooling load (via absorption chiller) is included in the heuristic CHP sizing calculation along with heating loads', null=True),
        ),
        migrations.AddField(
            model_name='chpinputs',
            name='months_serving_absorption_chiller_only',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]), blank=True, default=list, help_text='Months of the year in which the CHP only serves the absorption chiller load, only used if serve_absorption_chiller_only is True', size=None),
        ),
        migrations.AddField(
            model_name='chpinputs',
            name='serve_absorption_chiller_only',
            field=models.BooleanField(blank=True, default=False, help_text='Boolean indicator if CHP produced heat either serves absorption chiller or sends it to waste', null=True),
        ),
        migrations.AddField(
            model_name='chpoutputs',
            name='thermal_to_absorption_chiller_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, help_text='Thermal power to absorption chiller time-series array [MMBtu/hr]', size=None),
        ),
        migrations.AddField(
            model_name='cstoutputs',
            name='thermal_to_absorption_chiller_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='electricheateroutputs',
            name='thermal_to_absorption_chiller_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='existingboileroutputs',
            name='thermal_to_absorption_chiller_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='ghpoutputs',
            name='thermal_to_load_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='hightempthermalstorageoutputs',
            name='storage_to_absorption_chiller_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='hotthermalstorageoutputs',
            name='storage_to_absorption_chiller_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='steamturbineoutputs',
            name='thermal_to_absorption_chiller_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
    ]
