# Generated by Django 4.2.26 on 2026-05-14 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0114_rename_storage_to_turbine_series_mmbtu_per_hour_hightempthermalstorageoutputs_storage_to_steamturbin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coldthermalstorageinputs',
            name='installed_cost_per_gal',
            field=models.FloatField(blank=True, default=1.9, help_text='Installed cold TES cost in $/gal', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.AlterField(
            model_name='hotthermalstorageinputs',
            name='installed_cost_per_gal',
            field=models.FloatField(blank=True, default=1.9, help_text='Installed hot TES cost in $/gal', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
    ]
