# Generated by Django 4.2.26 on 2026-04-17 03:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0114_rename_storage_to_turbine_series_mmbtu_per_hour_hightempthermalstorageoutputs_storage_to_steamturbin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpoutputs',
            name='thermal_to_load_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
