# Generated by Django 4.2.26 on 2026-04-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0115_ghpoutputs_thermal_to_load_series_mmbtu_per_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chpinputs',
            name='include_cooling_in_chp_size',
        ),
        migrations.AlterField(
            model_name='chpinputs',
            name='follow_electrical_load',
            field=models.BooleanField(blank=True, default=False, help_text='Boolean indicator if CHP follows the electrical load by running at capacity or meeting the load only', null=True),
        ),
        migrations.AlterField(
            model_name='chpinputs',
            name='serve_absorption_chiller_only',
            field=models.BooleanField(blank=True, default=False, help_text='Boolean indicator if CHP produced heat either serves absorption chiller or sends it to waste', null=True),
        ),
    ]
