# Generated by Django 4.2.26 on 2026-05-15 22:25

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0115_alter_coldthermalstorageinputs_installed_cost_per_gal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricstorageoutputs',
            old_name='state_of_health',
            new_name='state_of_health_series_fraction',
        ),
        migrations.AddField(
            model_name='electricstorageinputs',
            name='fixed_soc_series_fraction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]), blank=True, default=list, help_text='If provided, SOC (as fraction of total energy capacity) will not be optimized and will instead be fixed to the values providedhere +- the absolute fixed_soc_series_fraction_tolerance. Must be an array of values 0-1 with length equal to 8760*time_steps_per_hour.', size=None),
        ),
        migrations.AddField(
            model_name='electricstorageinputs',
            name='fixed_soc_series_fraction_tolerance',
            field=models.FloatField(blank=True, help_text='Absolute tolerance on fixed_soc_series_fraction to avoid infeasible solutions when fixed_soc_series_fraction is provided.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
