# Generated by Django 4.2.26 on 2026-05-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0115_alter_coldthermalstorageinputs_installed_cost_per_gal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimeta',
            name='api_key',
            field=models.TextField(blank=True, default='', help_text='NLR Developer API key of the user'),
        ),
        migrations.AlterField(
            model_name='apimeta',
            name='job_type',
            field=models.TextField(default='developer.nlr.gov'),
        ),
    ]
