# Generated by Django 4.2.26 on 2026-06-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0116_alter_apimeta_api_key_alter_apimeta_job_type'),
        ('reoptjl', '0116_rename_state_of_health_electricstorageoutputs_state_of_health_series_fraction_and_more'),
    ]

    operations = [
    ]
