# Generated by Django 4.2.26 on 2026-04-27 21:26

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0116_remove_chpinputs_include_cooling_in_chp_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chpinputs',
            name='include_cooling_in_chp_size',
            field=models.BooleanField(blank=True, default=False, help_text='Boolean indicator if cooling load (via absorption chiller) is included in the heuristic CHP sizing calculation along with heating loads', null=True),
        ),
        migrations.AlterField(
            model_name='chpinputs',
            name='months_serving_absorption_chiller_only',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]), blank=True, default=list, help_text='Months of the year in which the CHP only serves the absorption chiller load, only used if serve_absorption_chiller_only is True', size=None),
        ),
    ]
