# Generated by Django 4.2.26 on 2026-08-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0114_chpoutputs_electric_curtailed_series_kw'),
        ('reoptjl', '0116_alter_apimeta_api_key_alter_apimeta_job_type'),
    ]

    operations = [
    ]
