# Generated by Django 4.2.26 on 2026-06-29 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0117_merge_20260530_1640'),
        ('reoptjl', '0117_merge_20260601_2056'),
    ]

    operations = [
    ]
