# Generated by Django 4.2.26 on 2026-05-02 14:53

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0117_chpinputs_include_cooling_in_chp_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chpinputs',
            name='months_serving_absorption_chiller_only',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]), blank=True, default=list, help_text='Months of the year in which the CHP only serves the absorption chiller load, only used if serve_absorption_chiller_only is True', size=None),
        ),
    ]
