# Generated by Django 4.2.26 on 2026-07-09 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0118_merge_20260629_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricstorageinputs',
            name='fixed_soc_series_fraction_tolerance',
            field=models.FloatField(blank=True, help_text='Absolute tolerance on fixed_soc_series_fraction to avoid infeasible solutions when fixed_soc_series_fraction is provided.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
