# Generated by Django 4.2.26 on 2026-07-15 19:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0120_electricstorageinputs_dispatch_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricstorageinputs',
            name='can_export_beyond_nem_limit',
            field=models.BooleanField(blank=True, default=False, help_text='True/False for if technology can export energy beyond the annual site load (and be compensated for that energy at the export_rate_beyond_net_metering_limit).'),
        ),
        migrations.AddField(
            model_name='electricstorageinputs',
            name='can_net_meter',
            field=models.BooleanField(blank=True, default=False, help_text='True/False for if technology has option to participate in net metering agreement with utility. Note that a technology can only participate in either net metering or wholesale rates (not both).'),
        ),
        migrations.AddField(
            model_name='electricstorageinputs',
            name='can_wholesale',
            field=models.BooleanField(blank=True, default=False, help_text='True/False for if technology has option to export energy that is compensated at the wholesale_rate. Note that a technology can only participate in either net metering or wholesale rates (not both).'),
        ),
        migrations.AddField(
            model_name='electricstorageoutputs',
            name='storage_to_grid_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, size=None),
        ),
    ]
