# Generated by Django 4.2.26 on 2026-08-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0117_merge_20260803_1544'),
        ('reoptjl', '0121_electricstorageinputs_can_export_beyond_nem_limit_and_more'),
    ]

    operations = [
    ]
