# Generated by Django 4.2.26 on 2026-08-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0123_chpinputs_existing_kw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chpinputs',
            name='follow_heating_load',
            field=models.BooleanField(blank=True, default=False, help_text='Boolean indicator if CHP follows the heating load by running at capacity or meeting the load only', null=True),
        ),
    ]
