# Generated by Django 4.2.26 on 2026-08-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0124_chpinputs_follow_heating_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='chpoutputs',
            name='annual_thermal_curtailed_mmbtu',
            field=models.FloatField(blank=True, help_text='Thermal energy wasted/unused/vented in a year [MMBtu]', null=True),
        ),
        migrations.AddField(
            model_name='chpoutputs',
            name='annual_thermal_curtailed_mmbtu_bau',
            field=models.FloatField(blank=True, help_text='Thermal energy wasted/unused/vented in a year by the existing CHP system in BAU [MMBtu]', null=True),
        ),
    ]
