import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0125_chpoutputs_annual_thermal_curtailed_mmbtu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chpinputs',
            old_name='supplementary_firing_capital_cost_per_kw',
            new_name='supplementary_firing_installed_cost_per_mmbtu_per_hour',
        ),
        migrations.RenameField(
            model_name='chpinputs',
            old_name='supplementary_firing_max_steam_ratio',
            new_name='supplementary_firing_max_ratio',
        ),
        migrations.RenameField(
            model_name='chpoutputs',
            old_name='size_supplemental_firing_kw',
            new_name='size_supplemental_firing_mmbtu_per_hour',
        ),
        migrations.AlterField(
            model_name='chpinputs',
            name='supplementary_firing_installed_cost_per_mmbtu_per_hour',
            field=models.FloatField(blank=True, default=20000.0, help_text='Installed CHP supplementary firing system cost in $/MMBtu/hr of incremental thermal capacity', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000000.0)]),
        ),
        migrations.AlterField(
            model_name='chpinputs',
            name='supplementary_firing_max_ratio',
            field=models.FloatField(blank=True, default=1.0, help_text='Ratio of max fired steam capacity relative to the steam generated by the CHP system when running at rated capacity. Relevant only for combustion_turbine prime_mover', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='chpoutputs',
            name='size_supplemental_firing_mmbtu_per_hour',
            field=models.FloatField(blank=True, help_text='Incremental thermal capacity of the CHP supplementary firing system [MMBtu/hr]', null=True),
        ),
        migrations.AddField(
            model_name='chpoutputs',
            name='size_supplementary_firing_ratio',
            field=models.FloatField(blank=True, help_text='Ratio of total fired thermal capacity (unfired + supplementary firing) to unfired CHP thermal capacity at full load [-]', null=True),
        ),
        migrations.AddField(
            model_name='chpoutputs',
            name='annual_supplementary_firing_thermal_production_mmbtu',
            field=models.FloatField(blank=True, help_text='Supplementary firing thermal energy produced in a year [MMBtu]', null=True),
        ),
    ]
