# Generated by Django 4.2.26 on 2026-10-01 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0125_chpoutputs_annual_thermal_curtailed_mmbtu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvinputs',
            name='outage_production_fraction',
            field=models.FloatField(blank=True, default=1.0, help_text='Fraction of production available during outages. Only applies with multiple outage modeling using inputs outage_start_time_steps and outage_durations.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='windinputs',
            name='outage_production_fraction',
            field=models.FloatField(blank=True, default=1.0, help_text='Fraction of production available during outages. Only applies with multiple outage modeling using inputs outage_start_time_steps and outage_durations.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
