# Generated by Django 4.2.26 on 2026-09-16 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0126_electricstorageinputs_size_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricstorageinputs',
            name='om_cost_fraction_of_installed_cost',
            field=models.FloatField(blank=True, default=0.04, help_text='Annual O&M cost as a fraction of installed cost.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='electricstorageinputs',
            name='size_class',
            field=models.IntegerField(blank=True, help_text='ElectricStorage size class. Must be an integer value between 1 and 4. Default is calculated per ratio of annual peak and average load of given load profile.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
