# Generated by Django 4.2.26 on 2026-09-22 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0126_rename_supplementary_firing_chp_fields_and_more'),
        ('reoptjl', '0128_alter_windinputs_om_cost_per_kw'),
    ]

    operations = [
    ]
