# Generated by Django 4.2.26 on 2026-10-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0126_pvinputs_outage_production_fraction_and_more'),
        ('reoptjl', '0129_merge_20260922_0441'),
    ]

    operations = [
    ]
