# Generated by Django 4.2.26 on 2026-03-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0016_alter_erpmeta_reopt_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpmeta',
            name='job_type',
            field=models.TextField(default='developer.nlr.gov'),
        ),
    ]
