apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: external
    contents:
      - path: tada-shared-kube
        git:
          url: https://github.nrel.gov/TADA/tada-shared-kube.git
          ref: origin/ports
