source "https://rubygems.org"

# Syncing production/staging data back to local environments.
gem "db-syncer", :require => false, :git => "https://github.nrel.gov/TADA/db-syncer.git", :branch => "main"

# Vault secrets as environment variables for development.
gem "vault_env_secrets", "~> 2.0.0"

# This isn't really a full Rails app, we're just using it for the db-syncer gem
# above to handle database dumps/restores for staging and development
# environments.
gem "rails", "~> 8.1.3"
gem "pg", "~> 1.6.3"
