source "https://rubygems.org", cooldown: 7

# Syncing production/staging data back to local environments.
gem "db-syncer", git: "https://github.nrel.gov/TADA/db-syncer.git", branch: "main", require: false

# Database setup tasks.
gem "rails-sql-tasks-enhancer", git: "https://github.nrel.gov/TADA/rails-sql-tasks-enhancer.git", branch: "main"

# Vault secrets as environment variables for development.
gem "vault_env_secrets", "~> 2.0.0"

# This isn't really a full Rails app, we're just using it for the db-syncer gem
# above to handle database dumps/restores for staging and development
# environments.
gem "rails", "~> 8.1.3"
gem "pg", "~> 1.6.3"
