name: Prune Deploy Images

on:
  schedule:
    - cron: "6 6 * * *" # Every day at 11:06 PM MST / 12:06 AM MDT
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vault-nonsensitive-secrets:
    name: Vault Non-Sensitive Secrets
    runs-on: self-hosted
    outputs:
      nonsensitive-secrets: ${{ steps.vault-nonsensitive-secrets.outputs.nonsensitive-secrets }}
    steps:
      - name: Import vault nonsensitive secrets
        id: vault-nonsensitive-secrets
        uses: TADA/vault-action/nonsensitive-secrets@v1
        with:
          template: |
            {{ with (datasource "vault" "reopt-api/ci/deploy").data }}
              {{ $secrets = coll.Merge (coll.Dict
                "container_registry" .container_registry
                "production_rancher_project_id" .production_rancher_project_id
                "staging_rancher_project_id" .staging_rancher_project_id
              ) $secrets }}
            {{ end }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}

  prune-images:
    name: Prune Deploy Images
    uses: TADA/deploy-action/.github/workflows/prune-deploy-images.yml@v2
    needs:
      - vault-nonsensitive-secrets
    with:
      vault-registry-credentials-path: secret/data/deploy/common/aws-ecr
      registry: ${{ fromJSON(needs.vault-nonsensitive-secrets.outputs.nonsensitive-secrets).container_registry }}
      images: |
        tada/reopt-api
      clusters: |
        - vault-kubeconfig-path: secret/data/deploy/staging/on-prem-rancher-test-ponderosa-cluster-test-reopt
          rancher-project-id: ${{ fromJSON(needs.vault-nonsensitive-secrets.outputs.nonsensitive-secrets).staging_rancher_project_id }}
        - vault-kubeconfig-path: secret/data/deploy/production/on-prem-rancher-ponderosa-cluster-reopt
          rancher-project-id: ${{ fromJSON(needs.vault-nonsensitive-secrets.outputs.nonsensitive-secrets).production_rancher_project_id }}
    secrets:
      vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
      vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
