name: Prune Deploy Images

on:
  schedule:
    - cron: "6 6 * * *" # Every day at 11:06 PM MST / 12:06 AM MDT
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vault-nonsensitive-secrets:
    name: Vault Non-sensitive Secrets
    uses: TADA/vault-action/.github/workflows/nonsensitive-secrets.yml@nonsensitive
    with:
      nonsensitive-secrets: |
        secret/data/reopt-api/ci/deploy container_registry ;
        secret/data/reopt-api/ci/deploy production_rancher_project_id ;
        secret/data/reopt-api/ci/deploy staging_rancher_project_id ;
    secrets:
      vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
      vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}

  prune-images:
    name: Prune Deploy Images
    uses: TADA/deploy-action/.github/workflows/prune-deploy-images.yml@v2
    needs:
      - vault-nonsensitive-secrets
    with:
      vault-registry-credentials-path: secret/data/deploy/common/aws-ecr
      registry: ${{ fromJSON(needs.vault-nonsensitive-secrets.outputs.nonsensitive-secrets).container_registry }}
      images: |
        tada/reopt-api
      clusters: |
        - vault-kubeconfig-path: secret/data/deploy/staging/on-prem-rancher-test-ponderosa-cluster-test
          rancher-project-id: ${{ fromJSON(needs.vault-nonsensitive-secrets.outputs.nonsensitive-secrets).staging_rancher_project_id }}
        - vault-kubeconfig-path: secret/data/deploy/production/on-prem-rancher-ponderosa-cluster-production
          rancher-project-id: ${{ fromJSON(needs.vault-nonsensitive-secrets.outputs.nonsensitive-secrets).production_rancher_project_id }}
    secrets:
      vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
      vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
